Port ibus-table from Python2 to Python3
I kept it working with Python2 for the moment, but in the long run
it is probably not worth the maintenance effort to keep it working
with Python2.

- I added stuff like

     if type(s) != type(u''):
         s = s.decode('UTF-8')

  for compatibility with Python2.

  http://docs.python.org/3/whatsnew/3.3.html says:

  > • The u'unicode' syntax is accepted again for str objects.

  So the above compatibility hack does not work for Python3 < 3.3.

- define our own compatibility function

    def ascii_ispunct(character):
        if character in '''!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~''':
            return True
        else:
            return False
  instead of using ascii.ispunct() from “from curses import ascii”
  to get the intended behaviour both in Python2 and Python3:

    $ python3
    Python 3.3.2 (default, Feb 19 2014, 14:35:19)
    [GCC 4.8.2 20131212 (Red Hat 4.8.2-7)] on linux
    Type "help", "copyright", "credits" or "license" for more information.
    >>> from curses import ascii
    >>> ascii.ispunct('.')
    True
    >>> ascii.ispunct('a')
    False
    >>> ascii.ispunct('☺')
    True
    >>> ascii.ispunct(u'a')
    False
    >>> ascii.ispunct(u'☺')
    True
    >>> ascii.ispunct(u'あ')
    True
    >>>

    $ python2
    Python 2.7.5 (default, Feb 19 2014, 13:47:28)
    [GCC 4.8.2 20131212 (Red Hat 4.8.2-7)] on linux2
    Type "help", "copyright", "credits" or "license" for more information.
    >>> from curses import ascii
    >>> ascii.ispunct('.')
    True
    >>> ascii.ispunct('a')
    False
    >>> ascii.ispunct('☺')
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/usr/lib64/python2.7/curses/ascii.py", line 63, in ispunct
        def ispunct(c): return _ctoi(c) != 32 and not isalnum(c)
      File "/usr/lib64/python2.7/curses/ascii.py", line 50, in _ctoi
        return ord(c)
    TypeError: ord() expected a character, but string of length 3 found
    >>> ascii.ispunct(u'a')
    True
    >>> ascii.ispunct(u'☺')
    True
    >>> ascii.ispunct(u'あ')
    True
    >>> ascii.ispunct(u'a'.encode('ascii'))
    False
    >>>

Python3